### ISSUE TITLE
Sneaky Blocks Bug

### ISSUE THREAD

**Issue by BGNDR** [Darkhax-Minecraft/Dark-Utilities#73] opened 2017-05-24 22:35 UTC
So I think I found a bug with the sneaky block. If I place the sneaky block down and the right click with carpet it and then try to remove the carpet it crashes the game. I tried it is single player creative then turned it survival and it crashed there too.

**Comment by darkhax** [comment] 2017-05-24 22:44
Hello, I need the full crash log to know what is actually going on. A crash log is always generated. You can find it here `profile folder/logs/fml-client-latest.log`

**Comment by BGNDR** [comment] 2017-05-24 22:56
[2017-05-24-1.log.gz](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/1027453/2017-05-24-1.log.gz)

**Comment by BGNDR** [comment] 2017-05-24 22:57
[2017-05-24-1.log.gz](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/1027454/2017-05-24-1.log.gz)

**Comment by darkhax** [comment] 2017-05-24 23:02
The log you sent is the server log. I need the client log.

**Comment by BGNDR** [comment] 2017-05-24 23:09
Just did it in single player here is the log
[First Player Crash.txt](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/1027469/First.Player.Crash.txt)

**Comment by darkhax** [comment] 2017-05-24 23:57
Okay, this issue was fixed some time ago and is a duplicate of #55 Please update to the latest version which you can find [here](https://minecraft.curseforge.com/projects/dark-utilities/files/2422077)

**Closed** 2017-05-24 23:57 UTC
Labels: duplicate
