### ISSUE TITLE
crashes from Monolith

### ISSUE THREAD

**Issue by JoeSGT** [Darkhax-Minecraft/Dark-Utilities#139] opened 2018-02-22 19:22 UTC
https://pastebin.com/cWjpwevv

```
Caused by: java.util.ConcurrentModificationException
at net.darkhax.darkutils.features.monolith.FeatureMonolith.onMobSpawnCheck(FeatureMonolith.java:92)
```
it seem i am getting crash because of that it's starting to happen often 
version i use it 1.12.2-1.8.193

**Comment by darkhax** [comment] 2018-02-28 02:14
I believe this issue is caused by code added by Sponge. You should make an issue on their issue tracker and link back here. If they disagree that the issue is on their end, then maybe they can help point out the flaw in my code. 

Relevant Code

```Java

    public static final Map<WorldServer, List<TileEntityMonolith>> LOADED_MONOLITHS = new HashMap<>();

    @SubscribeEvent
    public void onMobSpawnCheck (CheckSpawn event) {

        if (event.getWorld() instanceof WorldServer) {

            // This loop is cause of CME
            for (final TileEntityMonolith monolith : getMonoliths((WorldServer) event.getWorld())) {

                if (monolith.isInSameChunk(new BlockPos(event.getX(), event.getY(), event.getZ()))) {

                    monolith.onSpawnCheck(event);
                    break;
                }
            }
        }
    }

    public static List<TileEntityMonolith> getMonoliths (WorldServer world) {

        return LOADED_MONOLITHS.computeIfAbsent(world, key -> {
            return new ArrayList<>();
        });
    }
```

**Comment by Boomflex** [comment] 2018-03-03 01:00
Same as the above but not using Sponge

https://pastebin.com/PxgHU7pF

**Comment by Eufranio** [comment] 2018-03-03 05:42
If the world isn't in the map, computeIfAbsent will try to compute and add a new value to it (while you're iterating), hence why the CME.

**Comment by darkhax** [comment] 2018-03-03 16:57
Thanks for the insight @Eufranio There are actually a few ways that I was able to reproduce this issue. I have completely scrapped this system in favour of one that doesn't involve caching.

**Comment by Eufranio** [comment] 2018-03-03 16:58
You could call getMonoliths before start iterating and store it to a field. Would fix this issue.

**Comment by darkhax** [comment] 2018-03-10 06:52
This issue has been completely fixed in https://minecraft.curseforge.com/projects/dark-utilities/files/2539457

**Closed by darkhax** 2018-03-10 06:52 UTC
