### ISSUE TITLE
Server crash 

### ISSUE THREAD

**Issue by frenzye** [Darkhax-Minecraft/Dark-Utilities#74] opened 2017-05-25 22:24 UTC
https://gist.github.com/frenzye/42e99fc1fd069ffb8c1d91ae54e6ada5 could be related to https://minecraft.curseforge.com/projects/tf2-stuff-mod/issues/7

**Comment by frenzye** [comment] 2017-05-26 00:04
I don't think it's related to tf2 stuff mod, it's happening without https://gist.github.com/frenzye/5da81360638f8e250bf80250cb511af5

**Comment by darkhax** [comment] 2017-05-26 18:24
Thank you for reporting. This is a duplicate of https://github.com/Darkhax-Minecraft/Dark-Utilities/issues/68

**Closed by darkhax** 2017-05-26 18:24 UTC
Labels: duplicate
