### ISSUE TITLE
[1.12.2] Charms not working with Baubles

### ISSUE THREAD

**Issue by PapiDimmi** [Darkhax-Minecraft/Dark-Utilities#126] opened 2017-11-21 21:33 UTC
**Minecraft version**: 1.12.2
**Forge version**: 14.23.0.2531
**Dark Utilities version**: 1.7.182
**Baubles version**: 1.5.1

**Comment by 132ikl** [comment] 2017-11-26 04:55
+1

**Comment by darkhax** [comment] 2017-11-26 05:58
This is a duplicate of #119  

Baubles took so long to update that I removed support for it. Haven't had time to re-add the support.

**Closed by darkhax** 2017-11-26 05:58 UTC
