### ISSUE TITLE
Ender Tether Ticking Entity Crashes

### ISSUE THREAD

**Issue by Finalruner** [Darkhax-Minecraft/Dark-Utilities#78] opened 2017-06-02 04:00 UTC
https://pastebin.com/ELtDvSw0

#### Issue Description:
I've had a handful of crashes in a mod pack and after the last crash I've traced it back to the Ender tether used.

#### What happens:
When playing the crashes seemingly appear out of nowhere. Until you look at the crash report. As it turns out the 4 ender tethers I have set up around an EnderIO mob spawner for endermen is crashing the game. This could be caused by bad interaction between ender tethers and the inhibitor obelisk from EIO.

#### What you expected to happen:

When this happens I have to manually go into MC Edit and delete the enderman in order to get the game to load up w/o crashing again. Once the chunk loads with "ticking" endermen the game flips out.

#### Steps to reproduce:

1. Place down ender tethers in a chunk loaded area.
2. Wait for endermen to spawn
3. Cry
...

**Comment by darkhax** [comment] 2017-06-02 05:15
Which version are you using?

**Comment by leesdolphin** [comment] 2017-06-02 07:03
G'day I'm having a similar issue with `1.18.finalrc1`. I've put the [crash log](https://gist.github.com/leesdolphin/86dee7ba8b9d093d2620fc56444cb699) in a gist.

I'm currently debugging it on my local machine and i'll report back to see what's going wrong though I get the feeling that `entity.getCollisionBoundingBox()` is null

**Comment by leesdolphin** [comment] 2017-06-02 07:05
So I have confirmed that the problem is that the entity has a null bounding box. I will put up a PR momentarily to fix this

**Comment by Finalruner** [comment] 2017-06-03 16:24
This issue is present for me on version 1.1.8.finalrc1 for MC 1.10.2

**Comment by darkhax** [comment] 2017-06-03 16:58
This has been fixed on 1.10.2 thanks to leesdolphin. You can download finalrc2 [here](https://minecraft.curseforge.com/projects/dark-utilities/files/2428904). A fix to 1.11.2 will be out shortly.

**Closed** 2017-06-03 16:58 UTC
