### ISSUE TITLE
Vector Plates stop transporting

### ISSUE THREAD

**Issue by Meller127** [Darkhax-Minecraft/Dark-Utilities#32] opened 2016-12-29 12:51 UTC
Vector plates stops when no player is around even when the chunk is loaded.

Here is the setup, when i leave the area coal blocks will pile up in front of the dropper, when i return its starts moving again and a big pile of coal will start go around. The hole setup is within one chunk.

![2016-12-29_13 48 37](https://cloud.githubusercontent.com/assets/13392710/21544241/b5cdb5a2-cdcd-11e6-839a-46bb2539d0ad.png)

Minecraft: 1.10.2
Forge: 2185
Server: Yes
Chunkloaded: Yes, with EnderIO chunkloading wards. PowerGrid 360/500

**Comment by darkhax** [comment] 2017-01-17 03:48
This is a very interesting issue that I have not been able to reproduce. Do you have any further information about this?

**Comment by darkhax** [comment] 2017-01-30 17:25
Haven't been able to reproduce, closing due to lack of info.

**Closed by darkhax** 2017-01-30 17:25 UTC
